USE [master]
GO

/****** Object:  Database [sampledata]    Script Date: 9/5/2016 3:31:44 PM ******/
CREATE DATABASE [sampledata]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sampledata', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQL2014\MSSQL\DATA\sampledata.mdf' , SIZE = 40179712KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'sampledata_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQL2014\MSSQL\DATA\sampledata_log.ldf' , SIZE = 63424KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [sampledata] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sampledata].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sampledata] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sampledata] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sampledata] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sampledata] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sampledata] SET ARITHABORT OFF 
GO

ALTER DATABASE [sampledata] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sampledata] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sampledata] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sampledata] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sampledata] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sampledata] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sampledata] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sampledata] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sampledata] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sampledata] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sampledata] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sampledata] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sampledata] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sampledata] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sampledata] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sampledata] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sampledata] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sampledata] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sampledata] SET  MULTI_USER 
GO

ALTER DATABASE [sampledata] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sampledata] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sampledata] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sampledata] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [sampledata] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sampledata] SET  READ_WRITE 
GO


USE [sampledata]
GO

/****** Object:  Table [dbo].[Department]    Script Date: 9/5/2016 3:32:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Department](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
 CONSTRAINT [PK_department] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Person]    Script Date: 9/5/2016 3:33:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Person](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[first] [varchar](50) NULL,
	[last] [varchar](50) NULL,
	[department] [int] NOT NULL,
 CONSTRAINT [PK_person] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Person]  WITH CHECK ADD  CONSTRAINT [fk_department] FOREIGN KEY([department])
REFERENCES [dbo].[Department] ([id])
GO

ALTER TABLE [dbo].[Person] CHECK CONSTRAINT [fk_department]
GO